# CMake generated Testfile for 
# Source directory: /home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly
# Build directory: /home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(CMakeOnly.LinkInterfaceLoop "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=LinkInterfaceLoop" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
SET_TESTS_PROPERTIES(CMakeOnly.LinkInterfaceLoop PROPERTIES  TIMEOUT "90")
ADD_TEST(CMakeOnly.CheckSymbolExists "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=CheckSymbolExists" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.CheckCXXSymbolExists "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=CheckCXXSymbolExists" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.CheckCXXCompilerFlag "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=CheckCXXCompilerFlag" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.CheckLanguage "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=CheckLanguage" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.CompilerIdC "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=CompilerIdC" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.CompilerIdCXX "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=CompilerIdCXX" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.AllFindModules "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=AllFindModules" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.SelectLibraryConfigurations "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=SelectLibraryConfigurations" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.TargetScope "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=TargetScope" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.find_library "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=find_library" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.find_path "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=find_path" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.ProjectInclude "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=ProjectInclude" "-DCMAKE_ARGS=-DCMAKE_PROJECT_ProjectInclude_INCLUDE=/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/ProjectInclude/include.cmake" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.MajorVersionSelection-PythonLibs_2 "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.MajorVersionSelection-PythonLibs_3 "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.MajorVersionSelection-PythonInterp_2 "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.MajorVersionSelection-PythonInterp_3 "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.MajorVersionSelection-Qt_3 "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=MajorVersionSelection-Qt_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
ADD_TEST(CMakeOnly.MajorVersionSelection-Qt_4 "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DTEST=MajorVersionSelection-Qt_4" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=4;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/home/svm/openwrt_rtk/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeOnly/Test.cmake")
